"""
reconcile_claims.py — read-only reconciliation of what the existing results
actually say versus what the paper's Table 1 claims. Runs no models; only reads
JSON already in results/. Purpose: expose, before any rewrite or new experiment,
the gap between the 2-way (Laplace vs Gaussian) framing and the newer 4-way
(Laplace / Gaussian / Student-t / GGD) fits.

Usage:
    python scripts/reconcile_claims.py
"""
import json
import os
from collections import Counter

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(HERE, "results")

TWO_WAY = os.path.join(RES, "broader_analysis_results.json")     # paper Table 1 source (8 layers, 2-way)
FOUR_WAY = os.path.join(RES, "layerwise_model_comparison.json")  # newer 4-way fit, all layers

# GGD shape beta: 1.0 == Laplace, 2.0 == Gaussian, <1.0 == sharper-than-Laplace.
LAPLACE_BETA, GAUSS_BETA = 1.0, 2.0


def median(xs):
    xs = sorted(x for x in xs if x is not None)
    return xs[len(xs) // 2] if xs else None


def two_way_table():
    d = json.load(open(TWO_WAY))
    out = {}
    for r in d["results"]:
        pt = r["pretrained"]
        out[r["model_id"]] = pt.get("laplace_pct")
    return out, d.get("meta", {})


def four_way_table():
    d = json.load(open(FOUR_WAY))
    rows = []
    for r in d["results"]:
        mid = r["model_id"]
        layers = r["pretrained"]["layers"]
        n = len(layers)
        bic = Counter(l.get("bic_winner") for l in layers)
        # honest 2-way recomputation on THIS file's log-likelihoods, all layers:
        lap2 = sum(1 for l in layers if l["ll_laplace"] > l["ll_gaussian"])
        rows.append({
            "model_id": mid,
            "n_layers": n,
            "bic_winners": dict(bic),
            "plain_laplace_bic_wins": bic.get("Laplace", 0),
            "two_way_laplace_pct_alllayers": round(100 * lap2 / n, 1),
            "median_ggd_beta": round(median(l.get("ggd_beta") for l in layers), 3),
        })
    return rows


FAMILY = {
    "gpt2": "GPT", "gpt2-medium": "GPT", "gpt2-large": "GPT",
    "bert-base-uncased": "BERT", "bert-large-uncased": "BERT",
    "distilbert-base-uncased": "BERT", "albert-base-v2": "BERT",
    "roberta-base": "RoBERTa", "roberta-large": "RoBERTa", "distilroberta-base": "RoBERTa",
    "google/electra-small-discriminator": "ELECTRA",
    "facebook/bart-base": "EncDec", "t5-small": "EncDec", "t5-base": "EncDec",
    "google/mt5-small": "EncDec",
}


def regime_label(beta):
    if beta < 1.0:
        return "sub-Laplacian (very peaked)"
    if beta < 1.5:
        return "Laplacian-to-intermediate"
    if beta < 1.85:
        return "intermediate, near-Gaussian"
    return "Gaussian-like"


def write_markdown(paper_pct, rows, meta, path):
    lines = []
    lines.append("# Corrected distributional summary (auto-generated)")
    lines.append("")
    lines.append(f"> Generated by `scripts/reconcile_claims.py` from data already on disk. "
                 f"No models are run. Paper Table 1 basis: `broader_analysis_results.json` "
                 f"(first {meta.get('max_layers')} layers, 2-way Laplace/Gaussian). "
                 f"Columns below use `layerwise_model_comparison.json` (all layers, 4-way BIC fit).")
    lines.append("")
    lines.append("| Model | Family | Layers | Paper Lap% (2-way, 8L) | BIC winners (4-way, all layers) | Plain-Laplace BIC wins | Median GGD β | Regime |")
    lines.append("|---|---|---|---|---|---|---|---|")
    total_plain = 0
    for r in rows:
        mid = r["model_id"]
        total_plain += r["plain_laplace_bic_wins"]
        p = paper_pct.get(mid)
        pstr = f"{p:.1f}%" if p is not None else "n/a"
        beta = r["median_ggd_beta"]
        bicstr = ", ".join(f"{k} {v}" for k, v in r["bic_winners"].items())
        lines.append(f"| {mid} | {FAMILY.get(mid,'?')} | {r['n_layers']} | {pstr} | {bicstr} | "
                     f"{r['plain_laplace_bic_wins']} | {beta:.3f} | {regime_label(beta)} |")
    lines.append("")
    lines.append("## Headline reconciliation")
    lines.append("")
    peaked = [r["model_id"] for r in rows if r["median_ggd_beta"] < 1.0]
    lines.append(f"- **Layers best-fit by plain Laplace under BIC, across all 15 models: {total_plain}.** "
                 f"The paper's central noun is \"Laplace\"; under the 4-way BIC fit it wins zero layers. "
                 f"Winners are the generalized Gaussian (GGD) or Student-t.")
    lines.append(f"- **Models with median GGD β < 1 (sharper than Laplace, most compressible): {peaked}.** "
                 f"These encoder-decoder models — not the GPT family — carry the real quantization/pruning signal.")
    lines.append(f"- **\"BERT stays Gaussian\" does not hold under the 4-way fit.** BERT-family layers are "
                 f"predominantly best-fit by Student-t (heavy-tailed), not Gaussian.")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path, total_plain, peaked


def main():
    paper_pct, meta = two_way_table()
    rows = four_way_table()

    out_md = os.path.join(RES, "reconciliation_table.md")
    written, _, _ = write_markdown(paper_pct, rows, meta, out_md)
    print(f"Wrote {written}\n")

    print(f"Paper Table 1 basis: {TWO_WAY} (max_layers={meta.get('max_layers')}, 2-way Laplace/Gaussian)\n")
    hdr = f"{'model':34}{'paper Lap%':>11}{'4way BIC winners':>34}{'plainLap BIC':>13}{'med GGD beta':>14}"
    print(hdr)
    print("-" * len(hdr))
    total_plain_laplace = 0
    for r in rows:
        mid = r["model_id"]
        total_plain_laplace += r["plain_laplace_bic_wins"]
        p = paper_pct.get(mid)
        pstr = f"{p:.1f}" if p is not None else "n/a"
        beta = r["median_ggd_beta"]
        flag = "  <<peaked" if beta < LAPLACE_BETA else ""
        print(f"{mid:34}{pstr:>11}{str(r['bic_winners']):>34}{r['plain_laplace_bic_wins']:>13}{beta:>14.3f}{flag}")

    print("\nHeadline reconciliation:")
    print(f"  - Layers best-fit by *plain Laplace* under BIC, across all 15 models: {total_plain_laplace}")
    print("    (The paper's central noun is 'Laplace'. Under the 4-way BIC fit it wins zero layers.)")
    peaked = [r["model_id"] for r in rows if r["median_ggd_beta"] < LAPLACE_BETA]
    print(f"  - Models with median GGD beta < 1 (sharper than Laplace, most compressible): {peaked}")
    print("    (These, not the GPT family, carry the real quantization/pruning signal.)")


if __name__ == "__main__":
    main()
